### ISSUE TITLE
Newtypes questions

### ISSUE THREAD

**Issue by drybalka** [ornicar/scalalib#15] opened 2023-03-26 12:32 UTC
Hi, I am quite new to contributing to lichess and scala in general, but recently working with opaque types raised a few questions.

1) What is the point of `raw` method here https://github.com/ornicar/scalalib/blob/master/src/main/scala/newtypes.scala#L21 when the method `value` in the extension below is shorter and simpler? Why in some cases across lichess `raw` is used and in others `value`?
2) Shouldn't mathematical operations in `OpaqueInt` be allowed only for the instances of the same type? For example, in `+` method here https://github.com/ornicar/scalalib/blob/master/src/main/scala/newtypes.scala#L51 one can write (using types from chess.Clock)
```scala
LimitMinutes(1) + 1 // => LimitMinutes(2)
1 + LimitMinutes(1) // => does not compile
```
Moreover, even implicit conversions are allowed https://github.com/ornicar/scalalib/blob/master/src/main/scala/newtypes.scala#L59 which confusingly violates symmetry relation implied by the `+` operator:
```scala
LimitMinutes(1) + LimitSeconds(1) // => LimitMinutes(2)
LimitSeconds(1) + LimitMinutes(1) // => LimitSeconds(2)
```
Both are not the results one would desire. In this case it is almost the same as working directly with `Int`.
3) Maybe it is worth to add a multiplication operator, which, for example in my case, could have been useful to add host time depending on number of players:
```scala
inline infix def *(inline o: Int): A = apply(raw(a) * o)
```

**Comment by lenguyenthanh** [comment] 2023-06-23 19:57
Hi @drybalka,

I'll try my best to answers your question, but maybe @ornicar will have more insight on this.

1. There are two `raw` function in `TotalWrapper` trait, the first one is the same as `.value` as you said, the second one is a bit more powerful, when your variable is inside some type `M[_]`: `inline def raw[M[_]](inline f: M[Newtype]): M[Impl] = f.asInstanceOf[M[Impl]]`

So, that's why we use `.raw` sometime in lichess code base.

2. a) `LimitMinutes(1) + 1 // => LimitMinutes(2)` I think this is expected behavior, because it's still safe enough and more convenient than wrapping 1 into `LimitMinutes`.

b)
> 
> ```scala
> LimitMinutes(1) + LimitSeconds(1) // => LimitMinutes(2)
> LimitSeconds(1) + LimitMinutes(1) // => LimitSeconds(2)
> ```
> 
I think this is not ideal, maybe we should remove this feature, wdyt @ornicar ?

3.
> 
> ```scala
> inline infix def *(inline o: Int): A = apply(raw(a) * o)
> ```

I guess this is okay to add.

**Comment by ornicar** [comment] 2023-06-24 07:36
- https://github.com/ornicar/scalalib/blob/8ac0253f558043061d74fc4d1d18066a3f4eabf4/src/main/scala/newtypes.scala#L23 looks superfluous at worse indeed

- https://github.com/ornicar/scalalib/blob/8ac0253f558043061d74fc4d1d18066a3f4eabf4/src/main/scala/newtypes.scala#L30
is useful as it improves performance. Instead of `val i: List[Int] = seconds.map(_.value)` you can do `Second raw seconds` and avoid mapping.

```scala
LimitMinutes(1) + 1 // => LimitMinutes(2)
1 + LimitMinutes(1) // => does not compile
```
Not idea but better than nothing, as the first line has proven to be very useful in many situations.

 ```scala
LimitMinutes(1) + LimitSeconds(1) // => LimitMinutes(2)
LimitSeconds(1) + LimitMinutes(1) // => LimitSeconds(2)
```
That really sucks, thanks for pointing it out. Should be fixed.

```scala
inline infix def *(inline o: Int): A = apply(raw(a) * o)
```
can be added indeed. Please no division, or at least make it return an `Option` ;)

**Closed** 2023-06-24 08:23 UTC
